version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: supermarketlist-mongodb
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mision31
    volumes:
      - ~/mongodbdockerfiles:/data/db
      - ~/mongodbdockerfiles/log:/var/mongodb
    ports:
      - "27017:27017"
    

  mongo-express:
    image: mongo-express
    container_name: supermarketlist-mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mision31
      ME_CONFIG_MONGODB_URL: mongodb://root:mision31@mongo:27017/
  
  db:
    container_name: supermarketlist-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "mision31"
      MYSQL_DATABASE: "SuperMarketList"
      MYSQL_USER: "supermarketusers"
      MYSQL_PASSWORD: "EstaEsLaContraseniaNumero1234ParaDB"
    ports:
      - "3306:3306"
    volumes:
      - ~/mysqldockerfiles:/var/lib/mysql:rw

  adminer:
    container_name: supermarketlist-mysqladmin
    image: adminer
    restart: always
    ports:
      - 8091:8080