version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: supermarketlist-mongodb
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mision31
    volumes:
      - ~/mongodbdockerfiles:/data/db
      - ~/mongodbdockerfiles/log:/var/mongodb
    ports:
      - "27017:27017"
    
  db:
    container_name: supermarketlist-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "mision31"
      MYSQL_DATABASE: "SuperMarketList"
      MYSQL_USER: "supermarketusers"
      MYSQL_PASSWORD: "EstaEsLaContraseniaNumero1234ParaDB"
    ports:
      - "3306:3306"
    volumes:
      - ~/mysqldockerfiles:/var/lib/mysql:rw

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: '0:0'
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: mision31.
      MSSQL_PID: Enterprise
    volumes:
      - ~/docker/sqlserver-data:/home/server/sqlserverfiles