version: '3.1'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: '0:0'
    restart: always
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: mision31
      MSSQL_PID: Express
    volumes:
      - ~/docker/sqlserver-data:/home/server/sqlserverfiles
